#!/bin/sh
set -eu
print() { printf "%b%b" "${1-""}" "${2-"\\n"}"; }
stderr() { print "$@" >&2; }
reportError() {
	stderr "$2"
	return "$1"
}

if [ -n "${INVOKED_BY_INSTALLER+'x'}" ]; then
	reportError 1 "Fatal: INVOKED_BY_INSTALLER env is set which indicates a recursive call."
fi

vexec() {
	stderr "Executing: $*"
	"$@"
}

fetch() {
	if command -v curl >/dev/null; then
		vexec curl -fsSL "$1"
	else
		vexec wget -qO- "$1"
	fi
}

DOMAIN="${DOMAIN:-"github.com"}"
USERNAME="${USERNAME:-"MidnightRocket"}"
REPO_NAME="${REPO_NAME:-"linux-setup-scripts"}"
BASE_URL="${BASE_URL:-"https://${DOMAIN}/$USERNAME/$REPO_NAME"}"

BRANCH="${BRANCH:-"main"}"
REF="${REF:-"heads/$BRANCH"}"

export TAR_DOWNLOAD_PATH="${TAR_DOWNLOAD_PATH:-"$BASE_URL/archive/refs/${REF}.tar.gz"}"

cleanupTmpDir() { rm -rf "$TMP_DIR"; }
TMP_DIR="$(mktemp -d -p "/tmp")"
readonly TMP_DIR
export TMP_DIR
trap 'cleanupTmpDir; trap - EXIT' EXIT INT HUP TERM # Safely remove tmp dir on exit or interrupt

export SOURCE_DIR="$TMP_DIR/source"
mkdir "$SOURCE_DIR"

cd "$SOURCE_DIR"

fetch "$TAR_DOWNLOAD_PATH" | tar -xz -C "$SOURCE_DIR" --strip-components=1

export INSTALLER_LIB_DIR="$SOURCE_DIR/lib"
"$INSTALLER_LIB_DIR/install"
