#!/bin/sh

. "$INSTALLER_LIB_DIR/init"
. "$INSTALLER_LIB_DIR/require-root"

systemctl="$(commandv systemctl)"

baseName="updateroutine"
install -m 755 "$baseName" "/usr/local/sbin/$baseName"

# --- Create hook directory

configDir="/etc/updateroutine"
hooksDir="${configDir}/hooks"

if ! test -d "$hooksDir"; then
	vexec install -m 755 -d "$hooksDir"

	vexec cp -pr "hooks/." "$hooksDir"
fi

# --- Download systemd unit files
unitsDir="/etc/systemd/system"

serviceUnit="weekly-update.service"
baseName="$serviceUnit"
file="$unitsDir/$baseName"
vexec install -m 600 "systemd/$baseName" "$file"

timerUnit="weekly-update.timer"
baseName="$timerUnit"
file="$unitsDir/$baseName"
vexec install -m 600 "systemd/$baseName" "$file"

"$systemctl" enable --now "$timerUnit"
"$systemctl" status "$timerUnit"

stderr
stderr "To run update now use:"
stderr "\tsudo systemctl start $serviceUnit"
stderr
stderr "To view logs use: "
stderr "\tsudo journalctl -f -b -u $serviceUnit"

stderr
stderr "To disable automatic update use"
stderr "\tsudo systemctl disable $timerUnit"
stderr "and to cancel current timer use"
stderr "\tsudo systemctl stop $timerUnit"
