#!/bin/sh
[ -n "${COLOR_LOADED+'x'}" ] && return 0
COLOR_LOADED=1

# shellcheck disable=SC2034 # Allow unused variables

# CREDITS: https://github.com/MidnightRocket/posix-colors
if [ -z "${NO_COLOR+x}" ] && { [ -t 1 ] && [ -t 2 ] || [ -n "${CLICOLOR_FORCE+x}" ]; }; then readonly T_USE_COLOR=true; else unset T_USE_COLOR; fi
# Need to put this in variable on its own.
# It cannot be directly in parameter expansion below because then it won't work in bash and ksh
T_ESC="\033[" # ¯\_(ツ)_/¯
readonly T_ESC="${T_USE_COLOR+"$T_ESC"}"
###   -----   RESET FORMAT OR COLOR   -----   ###
readonly TR="${T_ESC}${T_USE_COLOR+"0m"}" TR_F="${T_ESC}${T_USE_COLOR+"39m"}" TR_B="${T_ESC}${T_USE_COLOR+"49m"}"
###   -----   TEXT FORMATTING   -----   ###
readonly T_BOLD="${T_ESC}${T_USE_COLOR+"1m"}" T_DIM="${T_ESC}${T_USE_COLOR+"2m"}" T_ITALIC="${T_ESC}${T_USE_COLOR+"3m"}" T_UNDERLINE="${T_ESC}${T_USE_COLOR+"4m"}"
readonly T_BLINK="${T_ESC}${T_USE_COLOR+"5m"}" T_REVERSE="${T_ESC}${T_USE_COLOR+"7m"}" T_HIDDEN="${T_ESC}${T_USE_COLOR+"8m"}" T_STRIKE="${T_ESC}${T_USE_COLOR+"9m"}"
###   -----   FOREGROUND COLORS   -----   ###
readonly TF_BLACK="${T_ESC}${T_USE_COLOR+"30m"}" TF_RED="${T_ESC}${T_USE_COLOR+"31m"}" TF_GREEN="${T_ESC}${T_USE_COLOR+"32m"}" TF_YELLOW="${T_ESC}${T_USE_COLOR+"33m"}" TF_BLUE="${T_ESC}${T_USE_COLOR+"34m"}" TF_MAGENTA="${T_ESC}${T_USE_COLOR+"35m"}" TF_CYAN="${T_ESC}${T_USE_COLOR+"36m"}" TF_DARK_GRAY="${T_ESC}${T_USE_COLOR+"90m"}"
readonly TF_WHITE="${T_ESC}${T_USE_COLOR+"97m"}" TF_BRIGHT_RED="${T_ESC}${T_USE_COLOR+"91m"}" TF_BRIGHT_GREEN="${T_ESC}${T_USE_COLOR+"92m"}" TF_BRIGHT_YELLOW="${T_ESC}${T_USE_COLOR+"93m"}" TF_BRIGHT_BLUE="${T_ESC}${T_USE_COLOR+"94m"}" TF_BRIGHT_MAGENTA="${T_ESC}${T_USE_COLOR+"95m"}" TF_BRIGHT_CYAN="${T_ESC}${T_USE_COLOR+"96m"}" TF_BRIGHT_GRAY="${T_ESC}${T_USE_COLOR+"37m"}"
###   -----   BACKGROUND COLORS   -----   ###
readonly TB_BLACK="${T_ESC}${T_USE_COLOR+"40m"}" TB_RED="${T_ESC}${T_USE_COLOR+"41m"}" TB_GREEN="${T_ESC}${T_USE_COLOR+"42m"}" TB_YELLOW="${T_ESC}${T_USE_COLOR+"43m"}" TB_BLUE="${T_ESC}${T_USE_COLOR+"44m"}" TB_MAGENTA="${T_ESC}${T_USE_COLOR+"45m"}" TB_CYAN="${T_ESC}${T_USE_COLOR+"46m"}" TB_DARK_GRAY="${T_ESC}${T_USE_COLOR+"100m"}"
readonly TB_WHITE="${T_ESC}${T_USE_COLOR+"107m"}" TB_BRIGHT_RED="${T_ESC}${T_USE_COLOR+"101m"}" TB_BRIGHT_GREEN="${T_ESC}${T_USE_COLOR+"102m"}" TB_BRIGHT_YELLOW="${T_ESC}${T_USE_COLOR+"103m"}" TB_BRIGHT_BLUE="${T_ESC}${T_USE_COLOR+"104m"}" TB_BRIGHT_MAGENTA="${T_ESC}${T_USE_COLOR+"105m"}" TB_BRIGHT_CYAN="${T_ESC}${T_USE_COLOR+"106m"}" TB_BRIGHT_GRAY="${T_ESC}${T_USE_COLOR+"47m"}"

# Helper functions for echoing/printing text.
# printf is fully posix compliant and is generally safer than echo.
# These auto resets formating
cprint() { printf "%b%b" "${1-""}" "${2-"${TR}\\n"}"; }
cstderr() { cprint "$@" 1>&2; }
