#!/bin/sh
set -eu

readonly URLS_FILE="${1?File must be given}"

if [ ! -f "$URLS_FILE" ]; then
	printf "%b" "'$URLS_FILE' not found!\n" 1>&2
	exit 1
fi

curl="$(command -v curl)"
awk="$(command -v awk)"

readonly OUTPUT_FILE="/dev/null"

AWK_PROG="$(
	cat <<-'EOF'
		NF == 0 || /^[[:space:]]*#/ {next}

		function handleSetting(setting) {
			if (setting == "token") {
				printf("header=\"Authorization: Bearer %s\";", $3)
				return
			}
			if (setting == "method") {
				printf("request=\"%s\";", toupper($3))
				return
			}
			printf("Setting '%s' is not valid!\n", $2) > "/dev/stderr"
			exit(1)
		}

		$1 == "use" {
			handleSetting($2)
			next
		}

		{
			printf("url=\"%s\"\n", $1)
		}
	EOF
)"

loadConfigs() {
	"$awk" "$AWK_PROG" "$1"
}

dispatch() {
	export _CONF
	_PIDS=""
	while read _CONF; do
		printenv _CONF | tr ';' '\n' | "$curl" --output "${OUTPUT:-"/dev/null"}" --no-progress-meter --fail --silent --show-error --max-time 10 --retry 5 --config - &
		_PIDS="$_PIDS $!"
		sleep 1
	done
	for p in $_PIDS; do
		wait "$p"
	done
}

loadConfigs "$URLS_FILE" | dispatch
