#!/bin/sh

# --- README --- #
# to run use
# curl -fsSL https://github.com/MidnightRocket/linux-update-scripts/raw/refs/heads/main/installer | sudo COMPONENTS=healthping/debian sh
#
#
# --- --- ---

. "$INSTALLER_LIB_DIR/init"
. "$INSTALLER_LIB_DIR/require-root"

install="$(commandv install)"
systemctl="$(commandv systemctl)"

APP_NAME="healthping"

binDir="/usr/local/bin"

configDir="/etc/$APP_NAME"
configUrlsFile="$configDir/urls"
if [ ! -d "$configDir" ]; then
	echo "Creating config dir in: $configDir"
	mkdir -m 755 "$configDir"
	install -m 600 "/dev/null" "$configUrlsFile"
	cat <<-EOF >"$configUrlsFile"
		# This is a comment
		# Put each url you want to ping on a line
	EOF
fi

baseName="$APP_NAME"
file="$binDir/$baseName"
install -m 755 "$baseName" "$file"

USER="_${APP_NAME}"
if ! id -u "$USER" >/dev/null 2>&1; then
	cstderr "${TF_BRIGHT_GREEN}Creating user $USER"
	useradd -U --home-dir /nonexistent -M -s /usr/sbin/nologin --system "$USER"
fi
chown "$USER:$USER" -R "$configDir"

# --- Download systemd unit files
unitsDir="/etc/systemd/system"

serviceUnit="${APP_NAME}.service"
baseName="$serviceUnit"
file="$unitsDir/$baseName"
install -m 644 "systemd/$baseName" "$file"

timerUnit="${APP_NAME}.timer"
baseName="$timerUnit"
file="$unitsDir/$baseName"
install -m 644 "systemd/$baseName" "$file"

vexec "$systemctl" enable --now "$timerUnit"
"$systemctl" status "$serviceUnit" || true

stderr
stderr "Ping urls are configured in '$configUrlsFile'"
