#!/bin/sh
set -eu

# --- README --- #
# to run use
# curl -fsSL https://github.com/MidnightRocket/linux-update-scripts/raw/refs/heads/main/installer | sudo COMPONENTS=debian sh
#
#
# --- --- ---

print() { printf "%b%b" "${1-""}" "${2-"\\n"}"; }
stderr() { print "$@" 1>&2; }

systemctl="$(command -v systemctl)"

vexec() {
	stderr "Executing: $*"
	"$@"
}

# POSIX compliant implementation
# https://stackoverflow.com/a/52586842
if [ "$(id -u)" -ne 0 ]; then
	stderr "Requires root!"
	exit 1
	# exec sudo "$0" "$@"
	# Automatically rerun script with root
fi

baseName="updateroutine"
install -m 755 "$baseName" "/usr/local/sbin/$baseName"

# --- Create hook directory

configDir="/etc/updateroutine"
hooksDir="${configDir}/hooks"

if ! test -d "$hooksDir"; then
	vexec install -m 755 -d "$hooksDir"

	vexec cp -pr "hooks/." "$hooksDir"
fi

# --- Download systemd unit files
unitsDir="/etc/systemd/system"

serviceUnit="weekly-update.service"
baseName="$serviceUnit"
file="$unitsDir/$baseName"
vexec install -m 600 "systemd/$baseName" "$file"

timerUnit="weekly-update.timer"
baseName="$timerUnit"
file="$unitsDir/$baseName"
vexec install -m 600 "systemd/$baseName" "$file"

"$systemctl" enable --now "$timerUnit"
"$systemctl" status "$timerUnit"

stderr
stderr "To run update now use:"
stderr "\tsudo systemctl start $serviceUnit"
stderr
stderr "To view logs use: "
stderr "\tsudo journalctl -f -b -u $serviceUnit"

stderr
stderr "To disable automatic update use"
stderr "\tsudo systemctl disable $timerUnit"
stderr "and to cancel current timer use"
stderr "\tsudo systemctl stop $timerUnit"
