#!/bin/sh
set -eu

# POSIX compliant implementation
# https://stackoverflow.com/a/52586842
if [ "$(id -u)" -ne 0 ]; then
	echo "Requires root!"
	exec sudo "$0" "$@"
	# Automatically rerun script with root
fi

msg="$(
	cat <<EOF
Update... Use: 
sudo journalctl -f -b -u weekly-update.service
To watch
EOF
)"

wall -n "$msg"

# --- Logging

runHook() {
	baseDir="/etc/updateroutine/hooks"
	script="${baseDir}/$1"
	echo "Running hook: $1"
	"$script"
}

# --- Pre apt routine

runHook pre-apt-hook

# --- Apt routine

apt update -q -y
apt full-upgrade -q -y
apt autoremove -q -y --purge

# --- Post apt routine

runHook post-apt-hook

# --- Reboot

if ! test -e "/var/run/reboot-required"; then
	echo "No reboot required"
	exit 0
fi

time="60"
msg="System reboot in $time second(s)"
wall -t 30 -n "$msg"
echo "$msg"

sleep "$time"

# On dietpi systems:
# https://github.com/MichaIng/DietPi/issues/4555#issuecomment-933622980
# Need to use with now

/usr/bin/systemctl --no-block --no-wall reboot
