#!/bin/sh
set -eu

if [ "$1" = "--update" ]; then
	echo "--update is nolonger supported!"
	exit 1
fi

configDir="/etc/dnsproxy-configs"

configFile="$configDir/config.conf"
if [ -x "$configFile" ]; then
	# https://stackoverflow.com/a/13702876
	. "$configFile"
else
	# Fallback to bare minimum configs
	arguments="-l 127.0.0.1 -p 53 -u tls://9.9.9.9 --cache "
fi

dnsproxy="/usr/local/bin/dnsproxy"
# Replace process with dnsproxy
# $arguments not qouted to because they need to be expanded
# not ideal but it what it is.
exec "$dnsproxy" $arguments
