#!/bin/sh
# --- README --- #
# to run use
# curl -fsSL https://github.com/MidnightRocket/linux-update-scripts/raw/refs/heads/main/installer | sudo COMPONENTS=dnsproxy/debian sh
#
#
# --- --- ---

. "$INSTALLER_LIB_DIR/init"
. "$INSTALLER_LIB_DIR/require-root"

binDir="/usr/local/bin"

baseName="dnsproxy-wrapper"
dst="$binDir/$baseName"
vexec install -m 755 "$baseName" "$dst"

# --- Create config directory

configDir="/etc/dnsproxy-configs"

if [ ! -d "$configDir" ]; then
	stderr "Creating config dir in: $configDir"
	vexec install -m 755 -d "$configDir"

	vexec cp -r "configs/." "$configDir"
fi

# https://github.com/joshcangit/dnsproxy-resolvconf/blob/4353c5e2cee12779c392947d09dae84504ac7a05/dnsproxy-setup.sh#L19
#
# use uname -m to get archtype
getArchtype() {
	arch="$(uname -m)"
	case "$arch" in
	*x86_64*)
		print "386"
		;;
	*aarch64*)
		print "arm64"
		;;
	esac
}

REPO="https://github.com/AdguardTeam/dnsproxy"
getLatestVersion() {
	curl -ISsf "${REPO}/releases/latest" | awk -F '[:/]' '$1 == "location" {sub("\r", "", $NF); print $NF}'
}

tar="$(command -v tar)"

cleanupTmpDir() { rm -rf "$TMP_DIR"; }
TMP_DIR="$(mktemp -d --suffix ".dnsproxy-downloader" -p "/tmp")"
readonly TMP_DIR
trap 'cleanupTmpDir; trap - EXIT' EXIT INT HUP TERM # Safely remove tmp dir on exit or interrupt

downloadDNSProxy() {
	stderr "Fetching DNS proxy"
	LATEST="$(getLatestVersion)"
	stderr "Latest version is '$LATEST'"
	PLATFORM="linux-$(getArchtype)"
	FILENAME="dnsproxy-$PLATFORM-$LATEST.tar.gz"
	URL="${REPO}/releases/download/${LATEST}/$FILENAME"
	stderr "Downloading from: $URL"
	curl -fsSL "$URL" -o "$TMP_DIR/$FILENAME" --compressed -H "Accept-Encoding: zstd, gzip, deflate"

	"$tar" -C "$TMP_DIR" --strip-components=2 -zxf "$TMP_DIR/$FILENAME" "./$PLATFORM/dnsproxy"
}

downloadDNSProxy

file="${TMP_DIR}/dnsproxy"

if [ -f "$file" ]; then
	stderr "success downloading file"
	stderr "Installing dnsproxy"
	vexec install -m 755 "$file" "$binDir/dnsproxy"
else
	stderr "Failed to download dnsproxy" 1>&2
	exit 1
fi

# --- Download systemd unit files
unitsDir="/etc/systemd/system"

serviceUnit="dnsproxy.service"
baseName="$serviceUnit"
file="$unitsDir/$baseName"
vexec install -m 600 "systemd/$baseName" "$file"

systemctl="$(command -v systemctl)"

user="_dnsproxy"

if [ "${MODE:-"install"}" = "update" ]; then
	vexec "$systemctl" stop "$serviceUnit"
	vexec "$systemctl" daemon-reload
	vexec "$systemctl" start "$serviceUnit"
else
	# Creates system user with no homedir, no login shell
	# And automatically creates matching group i.e. '_dnsproxy'
	useradd -U --home-dir /nonexistent -M -s /usr/sbin/nologin --system "$user"

	# Make dnsproxy user owner of $configDir
	chown "$user":"$user" -R "$configDir"

	vexec "$systemctl" enable --now "$serviceUnit"
fi

"$systemctl" status $serviceUnit

stderr
stderr "To restart service use"
stderr "\tsudo systemctl restart $serviceUnit"
stderr
stderr "To view logs use: "
stderr "\tsudo journalctl -f -b -u $serviceUnit"
